module.exports = function ( io, session ) {
    
    // hook up a session under this route
    session ( io.of ( '/category' ), open, dispatch, close );
    
    // socketId is the number generated by our code at the server
    // the internal id of the socket is different, generated by socket.io
    
    // ns is the namespaced io channel
    
    // db is our database
    
    // session is opened in the "category" namespace
    function open ( ns, socket, socketId, db ) {
        var id;
        ns.on ( 'user', function ( user ) {
            // broadcast to all except sender
            socket.broadcast.emit ( 'join', user );
            id = user;
        } );
        
        return id;
    }
    
    // define dispatch routes here
    function dispatch ( ns, socket, socketId, db, user ) {
        ns.on ( 'create', function ( create ) {
            var query = db.query ( )
        } );
        
        ns
    }
    
    // session is closing/disconnecting
    function close ( ns, socket, socketId, db ) {
        
    }
};